apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: buildpacks-app-image
spec:
  type: image
  params:
    - name: url
      value: test.azurecr.io/node-docker-example ## Registry URL
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: buildpacks-test-pipeline
spec:
  workspaces:
    - name: shared-workspace
  resources:
    - name: build-image
      type: image
  tasks:
    - name: fetch-repository # This task fetches a repository from github, using the `git-clone` task we installed
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/buildpacks/samples
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: buildpacks # This task uses the `buildpacks` task to build the application
      taskRef:
        name: buildpacks
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: SOURCE_SUBPATH
          value: "apps/java-maven" # This is the path within our samples repo we want to build
        - name: BUILDER_IMAGE
          value: "paketobuildpacks/builder:base" # This is the builder we want the task to use
        - name: CACHE
          value: buildpacks-cache
      resources:
        outputs:
          - name: image
            resource: build-image
